[package]
name = "l70_P5ICT_DLL"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.8.1"
windows = {version = "0.62.2", features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"]}

[lib]
crate-type = ["cdylib"]
